services:
  - docker:dind

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
  IMGNAME: "digital-front"
  DOCKER_HUB_USER: "$DOCKER_HUB_USERNAME"
  DOCKER_HUB_PASSWORD: "$DOCKER_HUB_PASSWORD"
  BASE_API_URL: "$BASE_API_URL"
  BASE_YANDEX_API_URL: "$BASE_YANDEX_API_URL"
  YANDEX_REDIRECT_URI: "$YANDEX_REDIRECT_URI"
  YANDEX_CLIENT_ID: "$YANDEX_CLIENT_ID"
  YANDEX_CLIENT_SECRET: "$YANDEX_CLIENT_SECRET"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        ENVIRONMENT_NAME: production
        HOST: igniz.ru
    - if: $CI_COMMIT_BRANCH == "stage"
      variables:
        ENVIRONMENT_NAME: stage
        HOST: igniz.ru

stages:
  - build
  - deploy

build:
  image: docker:stable
  stage: build
  environment:
    name: $ENVIRONMENT_NAME
  tags:
    - $ENVIRONMENT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - echo "Building Docker image..."
    # - cat "$ENV_FILE"
    # - export $(cat "$ENV_FILE" | xargs)
    # - echo "DEBUG BASE_YANDEX_API_URL=$BASE_YANDEX_API_URL"
    - sh ./env-as-build-args.sh $ENV_FILE | xargs docker build -t $TAG_COMMIT -t $TAG_LATEST .
    # - docker build --build-arg ENV_FILE="$ENV_FILE" -t $TAG_COMMIT -t $TAG_LATEST .
    # - docker build --build-arg BASE_API_URL=$BASE_API_URL --build-arg BASE_YANDEX_API_URL=$BASE_YANDEX_API_URL --build-arg YANDEX_REDIRECT_URI=$YANDEX_REDIRECT_URI --build-arg YANDEX_CLIENT_ID=$YANDEX_CLIENT_ID --build-arg YANDEX_CLIENT_SECRET=$YANDEX_CLIENT_SECRET -t $TAG_COMMIT -t $TAG_LATEST .

deploy:
  image: docker:stable
  stage: deploy
  tags:
    - $ENVIRONMENT_NAME
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    - docker container rm -f $IMGNAME || true
    - docker run -d --restart unless-stopped -p 5173:5173 --name $IMGNAME $TAG_COMMIT
  after_script:
    - docker system prune -a -f
